### PR TITLE
new 

### PR DESCRIPTION
**Pull request by SahilChoudhary998**
with the folders and new vid

### CODE REVIEW

**Comment by KatyaSr** [comment]
It required to install 3 libraries.
Still doesn't run and gives warnings:

Compiled with warnings.

src/pages/Navbar/SignIn.js
  Line 6:8:  'Link' is defined but never used  no-unused-vars

src/pages/Navbar/SignUp.js
  Line 2:9:  'Link' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in src/pages/Navbar/SignIn.js
  Line 6:8:  'Link' is defined but never used  no-unused-vars

src/pages/Navbar/SignUp.js
  Line 2:9:  'Link' is defined but never used  no-unused-vars

webpack compiled with 1 warning

**Comment by KatyaSr** [comment]
Also, whats Subway - 6398.mp4 supposed to have in it? Content doesn't show on github

Compiled with problems:X

ERROR in ./src/App.js 14:0-48

Module not found: Error: Can't resolve './assets/Subway - 6398.mp4'

**Comment by SahilChoudhary998** [comment]
Subway m4 is the new video I used for the background and what exact errors are you getting? Im not sure how it's not running when its being compiled. What compile errors are you getting we can ignore the warnings for now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KatyaSr** [comment]
Compiled with problems:X

ERROR in ./src/App.js 14:0-48

Module not found: Error: Can't resolve './assets/Subway - 6398.mp4'

**Comment by KatyaSr** [comment]
I fixed the error but now it just opens to a white screen on npm start

**Comment by KatyaSr** [comment]
Yuxuan, does it work for you?

**Pull request merged**
